version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\go-siris\siris

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get ./...
  # install test dependencies
  - go get golang.org/x/tools/cmd/cover
  - go get -v github.com/axw/gocov
  - go install github.com/axw/gocov/gocov

test_script:
  - for /f "" %%G in ('go list ./... ^| find /i /v "/vendor/"') do ( gocov test %%G & IF ERRORLEVEL == 1 EXIT 1)

branches:
  only:
    - master

build: false
deploy: false